In [1]:
import pandas as pd

In [14]:
import os

print(os.getcwd())

c:\Users\91830\OneDrive\Desktop\E_commerce

In [15]:
print(os.listdir())

['data', 'data.ipynb', 'data_preprocessing.ipynb', 'eda.ipynb', 'label_encoder.pkl', 'scaler.pkl']

In [16]:
print(os.getcwd())
print(os.listdir())

c:\Users\91830\OneDrive\Desktop\E_commerce
['data', 'data.ipynb', 'data_preprocessing.ipynb', 'eda.ipynb', 'label_encoder.pkl', 'scaler.pkl']

In [17]:
import os

print(os.listdir("data"))

['ecommerce_sessions.csv']

In [ ]:
df = pd.read_csv("data/ecommerce_sessions.csv")

In [3]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Converted
0,1,14.6517,0,0.0000,19,283.8812,0.008014,0.042106,68.579222,0.0,June,1,2,1,1,Returning_Visitor,False,1
1,1,18.9189,2,54.9802,15,1241.7638,0.032395,0.058101,0.000000,0.0,May,2,1,8,12,Returning_Visitor,False,0
2,1,30.0198,0,0.0000,23,365.3384,0.006802,0.029451,0.000000,0.0,Mar,1,2,1,3,New_Visitor,True,0
3,1,6.5566,0,0.0000,6,687.4788,0.039577,0.104395,0.000000,0.6,Dec,1,1,1,2,Returning_Visitor,True,0
4,1,112.5842,1,36.3523,19,656.4535,0.004594,0.038321,0.000000,0.0,Mar,2,1,2,5,Returning_Visitor,False,0

In [4]:
df.shape

(12000, 18)

In [5]:
df.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Converted'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12000 non-null  int64
 1   Administrative_Duration  12000 non-null  float64
 2   Informational            12000 non-null  int64
 3   Informational_Duration   12000 non-null  float64
 4   ProductRelated           12000 non-null  int64
 5   ProductRelated_Duration  12000 non-null  float64
 6   BounceRates              12000 non-null  float64
 7   ExitRates                12000 non-null  float64
 8   PageValues               12000 non-null  float64
 9   SpecialDay               12000 non-null  float64
 10  Month                    12000 non-null  str
 11  OperatingSystems         12000 non-null  int64
 12  Browser                  12000 non-null  int64
 13  Region                   12000 non-null  int64
 14  TrafficType              12000 non-null  int64
 15  VisitorType              12000 non-null  str
 16  Weekend                  12000 non-null  bool
 17  Converted                12000 non-null  int64
dtypes: bool(1), float64(7), int64(8), str(2)
memory usage: 1.8 MB

In [7]:
df.describe()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType,Converted
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,1.888667,42.311715,0.545667,13.548495,19.832083,723.097053,0.021219,0.054104,12.229337,0.061117,2.445083,2.538917,3.301167,10.557167,0.157167
std,1.465361,49.031915,0.754848,25.073544,13.170700,763.561517,0.015549,0.026335,25.858819,0.204577,1.730578,2.446832,2.315508,5.809393,0.363973
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,1.000000,11.768900,0.000000,0.000000,11.000000,268.158750,0.008306,0.035625,0.000000,0.000000,1.000000,1.000000,1.000000,6.000000,0.000000
50%,2.000000,28.511250,0.000000,0.000000,17.000000,499.425850,0.020064,0.053757,0.000000,0.000000,2.000000,2.000000,3.000000,11.000000,0.000000
75%,3.000000,56.383875,1.000000,19.933500,25.000000,902.039425,0.031951,0.071956,12.913332,0.000000,3.000000,3.000000,5.000000,16.000000,0.000000
max,11.000000,659.468000,6.000000,397.166500,156.000000,10154.158900,0.088727,0.158354,418.113564,1.000000,8.000000,13.000000,9.000000,20.000000,1.000000

In [8]:
df.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Converted                  0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)