In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv(r"C:\Users\91830\Downloads\0a6abcf71b8ee7c084d328b9ef2f0651\ecommerce_sessions.csv")
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Converted
0,1,14.6517,0,0.0000,19,283.8812,0.008014,0.042106,68.579222,0.0,June,1,2,1,1,Returning_Visitor,False,1
1,1,18.9189,2,54.9802,15,1241.7638,0.032395,0.058101,0.000000,0.0,May,2,1,8,12,Returning_Visitor,False,0
2,1,30.0198,0,0.0000,23,365.3384,0.006802,0.029451,0.000000,0.0,Mar,1,2,1,3,New_Visitor,True,0
3,1,6.5566,0,0.0000,6,687.4788,0.039577,0.104395,0.000000,0.6,Dec,1,1,1,2,Returning_Visitor,True,0
4,1,112.5842,1,36.3523,19,656.4535,0.004594,0.038321,0.000000,0.0,Mar,2,1,2,5,Returning_Visitor,False,0

In [3]:
df.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Converted                  0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
X = df.drop("Converted", axis=1)

y = df["Converted"]

In [6]:
X.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
0,1,14.6517,0,0.0000,19,283.8812,0.008014,0.042106,68.579222,0.0,June,1,2,1,1,Returning_Visitor,False
1,1,18.9189,2,54.9802,15,1241.7638,0.032395,0.058101,0.000000,0.0,May,2,1,8,12,Returning_Visitor,False
2,1,30.0198,0,0.0000,23,365.3384,0.006802,0.029451,0.000000,0.0,Mar,1,2,1,3,New_Visitor,True
3,1,6.5566,0,0.0000,6,687.4788,0.039577,0.104395,0.000000,0.6,Dec,1,1,1,2,Returning_Visitor,True
4,1,112.5842,1,36.3523,19,656.4535,0.004594,0.038321,0.000000,0.0,Mar,2,1,2,5,Returning_Visitor,False

In [8]:
y.head()

0    1
1    0
2    0
3    0
4    0
Name: Converted, dtype: int64

In [9]:
X.select_dtypes(include="object").columns

C:\Users\91830\AppData\Local\Temp\ipykernel_19860\2213039483.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(include="object").columns

Index(['Month', 'VisitorType'], dtype='str')

In [10]:
encoder = LabelEncoder()

X["Month"] = encoder.fit_transform(X["Month"])

X["VisitorType"] = encoder.fit_transform(X["VisitorType"])

In [11]:
X.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
0,1,14.6517,0,0.0000,19,283.8812,0.008014,0.042106,68.579222,0.0,4,1,2,1,1,2,False
1,1,18.9189,2,54.9802,15,1241.7638,0.032395,0.058101,0.000000,0.0,6,2,1,8,12,2,False
2,1,30.0198,0,0.0000,23,365.3384,0.006802,0.029451,0.000000,0.0,5,1,2,1,3,0,True
3,1,6.5566,0,0.0000,6,687.4788,0.039577,0.104395,0.000000,0.6,1,1,1,1,2,2,True
4,1,112.5842,1,36.3523,19,656.4535,0.004594,0.038321,0.000000,0.0,5,2,1,2,5,2,False

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [13]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(9600, 17)
(2400, 17)
(9600,)
(2400,)

In [14]:
scaler = StandardScaler()

In [15]:
X_train = scaler.fit_transform(X_train)

In [16]:
X_test = scaler.transform(X_test)

In [17]:
X_train

array([[ 0.0683354 , -0.25677401, -0.7273363 , ..., -1.6405306 ,
         0.39620788,  1.8110721 ],
       [-0.6143075 , -0.23851832, -0.7273363 , ..., -0.77846405,
         0.39620788, -0.55215913],
       [-1.29695039, -0.86047212, -0.7273363 , ...,  1.46290898,
         0.39620788, -0.55215913],
       ...,
       [-1.29695039, -0.86047212, -0.7273363 , ...,  0.25601581,
         0.39620788, -0.55215913],
       [ 0.0683354 ,  0.17751904,  1.92153641, ...,  0.94566905,
         0.39620788, -0.55215913],
       [-0.6143075 , -0.42539262,  3.24597276, ...,  1.63532229,
        -2.58466643, -0.55215913]], shape=(9600, 17))

In [18]:
import joblib

joblib.dump(scaler, "scaler.pkl")
joblib.dump(encoder, "label_encoder.pkl")

['label_encoder.pkl']